### PR TITLE
League of justice

### PR DESCRIPTION
**Pull request by Hatallia**
Changes that allows to gather equal portions of tweets for each
participant

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Thank you @Hatallia 
Do you want  me to make the code shorter or just merge ?)

**Comment by Hatallia** [comment]
@sergey-tihon ))) you decide. I don't mind refactoring, go ahead if needed.

**Comment by sergey-tihon** [comment]
not sure that i understand your chunking approach...

Do we need to split by date when we split by participants?
Or maybe we need to split each day by participants?

As I understand the oldest day contains tweets that you already read.
Now, all tweets from this day come to exactly one participant and he may skip this day.

**Comment by sergey-tihon** [comment]
Maybe something like this?

``` fsharp
let rec split length (xs: list<'T>) =
  [ yield List.truncate length xs
    if xs.Length > length then
        yield! split length (List.skip length xs) ]

filteredTweets
|> List.groupBy (fun x-> getGroupKey x.CreatedDate)
|> List.iter (fun ((week,day,dw),tweets) ->
    tweets
    |> split ((tweets.Length + participants.Length - 1) / participants.Length) // Chunk size
    |> List.zip (List.ofArray participants)
    |> List.filter (fun (_,tweets) -> tweets.Length > 0)
    |> List.iter (fun (name, tweetsForUser: TwitterStatus list) ->
        let fileName = sprintf "Tweets__%s__Week%d__Day%d_%A.html" name week day dw
        printTweetsInHtml fileName tweetsForUser
    )
)
```

Resulting folder:
image

**Comment by Hatallia** [comment]
Recurrent function is a good one, thank you. Splitting by participants and then by day as well as creating folders is what I did manually, therefore, it seemed to me logical to automate it like this. I would not go with your "all days for everyone" approach, because I want users to receive just one or two files, not many. @sergey-tihon

**Comment by sergey-tihon** [comment]
New resulting folder:
image

**Pull request merged**
